### ISSUE TITLE
Add support for BasicAuth

### ISSUE THREAD

**Issue by hcw70** [tortilla/tortilla#41]
I am trying to use your library to access a Jama rest service.

This however requires HTTP Basic Auth.

It would be great if your library could add support for this, maybe by forwarding the auth object to the
request library as described in:
http://docs.python-requests.org/en/master/user/authentication/

So` client code could become like 

```
from requests.auth import HTTPBasicAuth
import tortilla
api = tortilla.wrap('https://api.example.org')
api.config.auth = HTTPBasicAuth('user', 'pass')
```

or maybe 
`
from tortilla import HTTPBasicAuth
`

**Comment by medecau** [comment]
I suggest adding it to the initial wrap() as an argument.

**Comment by medecau** [comment]
I think PR #37 solves this.

**Comment by redodo** [comment]
PR #37 indeed solves this issue. With the next release it will be possible to add HTTP Basic Authentication in the following way:
```python
import tortilla
from requests.auth import HTTPBasicAuth

api = tortilla.wrap('https://api.example.org', auth=HTTPBasicAuth('user', 'pass'))
```
